# Generated by Django 4.2.8 on 2024-02-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Haber',
        ),
    ]
