# Generated by Django 4.2.8 on 2024-02-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_rename_blog_haber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haberust1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('date_now', models.DateTimeField(verbose_name='Tarih - Saat')),
                ('author', models.CharField(max_length=50, verbose_name='Yazar')),
                ('image', models.ImageField(max_length=250, upload_to='profile', verbose_name='Haber Resmi')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category')),
            ],
        ),
    ]
