# Generated by Django 4.2.8 on 2024-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_bulten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('date_now', models.DateTimeField(verbose_name='Tarih - Saat')),
            ],
        ),
    ]
