# Generated by Django 4.2.8 on 2024-02-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='detay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.haberust1', verbose_name='Haberust1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat'),
        ),
    ]
