# Generated by Django 4.2.8 on 2024-02-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_comment_detay_alter_comment_date_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='detay',
            new_name='blog',
        ),
    ]
