# Generated by Django 4.2.8 on 2024-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_rename_detay_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('last_name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('username', models.CharField(max_length=50, verbose_name='Başlık')),
                ('email', models.CharField(max_length=50, verbose_name='Başlık')),
                ('password', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
        ),
    ]
