# Generated by Django 4.2.8 on 2024-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0015_uyeler'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeler',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='profile', verbose_name='Profile Resmi'),
        ),
    ]
