# Generated by Django 4.2.8 on 2024-02-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0016_uyeler_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeler',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='Girişli Profil'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Şifre'),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
