# Generated by Django 4.2.8 on 2024-02-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0017_uyeler_islogin_alter_uyeler_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeler',
            name='gizlisoru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='gizlisoru'),
        ),
    ]
