# Generated by Django 4.2.8 on 2024-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0019_alter_uyeler_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeler',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='profile', verbose_name='Haber Resmi'),
        ),
    ]
