# Generated by Django 4.2.8 on 2024-02-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0021_alter_uyeler_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='proimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/', verbose_name='Profil resmi')),
                ('aktifresim', models.BooleanField(default=False, verbose_name='aktif Resim')),
                ('uyeler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.uyeler')),
            ],
        ),
    ]
