# Generated by Django 4.2.8 on 2024-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0022_proimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proimage',
            name='aktifresim',
            field=models.BooleanField(default=True, verbose_name='aktif Resim'),
        ),
    ]
