# Generated by Django 4.2.8 on 2024-02-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0023_alter_proimage_aktifresim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proimage',
            name='uyeler',
        ),
        migrations.AddField(
            model_name='proimage',
            name='uyeid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Üye id'),
        ),
        migrations.AlterField(
            model_name='proimage',
            name='aktifresim',
            field=models.BooleanField(default=False, verbose_name='aktif Resim'),
        ),
    ]
