# Generated by Django 4.2.8 on 2024-02-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0024_remove_proimage_uyeler_proimage_uyeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proimage',
            old_name='uyeid',
            new_name='uyeler',
        ),
    ]
