# Generated by Django 4.2.8 on 2024-02-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0026_proimage_islogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proimage',
            name='islogin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.uyeler'),
        ),
    ]
