# Generated by Django 4.2.8 on 2024-02-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0027_alter_proimage_islogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proimage',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='Girişli Profil'),
        ),
    ]
