# Generated by Django 4.2.8 on 2024-02-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0030_alter_proimage_islogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proimage',
            old_name='islogin',
            new_name='username',
        ),
    ]
