# Generated by Django 4.2.8 on 2024-02-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0031_rename_islogin_proimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proimage',
            name='username',
        ),
    ]
