# Generated by Django 4.2.8 on 2024-02-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0032_remove_proimage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='proimage',
            name='islogin',
            field=models.BooleanField(default=False, verbose_name='Girişli Profil'),
        ),
    ]
