# Generated by Django 4.2.8 on 2024-02-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0035_alter_proimage_uyeler2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proimage',
            name='uyeler2',
        ),
    ]
